apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack-charts
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: loki-stack
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 2.9.10
    helm:
      values: |
        loki:
          enabled: true
          isDefault: true
          url: http://{{(include "loki.serviceName" .)}}:{{ .Values.loki.service.port }}
          readinessProbe:
            httpGet:
              path: /ready
              port: http-metrics
            initialDelaySeconds: 45
          livenessProbe:
            httpGet:
              path: /ready
              port: http-metrics
            initialDelaySeconds: 45
          datasource:
            jsonData: "{}"
            uid: ""


        promtail:
          enabled: true
          config:
            logLevel: info
            serverPort: 3101
            clients:
              - url: http://{{ .Release.Name }}:3100/loki/api/v1/push

        fluent-bit: 
          enabled: false

        grafana:
          enabled: true
          image:
            tag: "latest"
          service:
            type: LoadBalancer
          adminPassword: "flow@grafana"
          datasources:
            datasources.yaml:
              apiVersion: 1
              datasources:
                - name: Loki
                  type: loki
                  url: http://loki.monitoring:3100
                  access: proxy
                  isDefault: true

        prometheus:
          enabled: true
          alertmanager:
            enabled: true
            persistentVolume:
              enabled: false
          server:
            enabled: true
            persistentVolume:
              enabled: false
            resources:
              limits:
                cpu: 1
                memory: 1Gi
              requests:
                cpu: 500m
                memory: 512Mi
          pushgateway:
            enabled: true
            persistentVolume:
              enabled: false
          nodeExporter:
            enabled: true
            resources:
              limits:
                cpu: 100m
                memory: 128Mi
              requests:
                cpu: 50m
                memory: 64Mi
