apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack-charts
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: flow
  source:
    chart: loki-stack
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 2.10.2
    helm:
      values: |
        loki:
          enabled: true
          persistence:
            enabled: true
            storageClassName: standard
            size: 5Gi
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          tolerations:
            - key: "instance_type"
              operator: "Equal"
              value: "spot"
              effect: "NoSchedule"

        promtail:
          enabled: true
          config:
            clients:
              - url: http://loki-stack-charts:3100/loki/api/v1/push
            positions:
              filename: /run/promtail/positions.yaml
            scrape_configs:
              - job_name: kubernetes-pods
                kubernetes_sd_configs:
                  - role: pod
                relabel_configs:
                  - source_labels: [__meta_kubernetes_pod_label_name]
                    target_label: __service__
                  - source_labels: [__meta_kubernetes_namespace]
                    target_label: namespace
                  - source_labels: [__meta_kubernetes_pod_name]
                    target_label: pod_name
                  - source_labels: [__meta_kubernetes_pod_container_name]
                    target_label: container_name
                  - action: replace
                    source_labels: [__meta_kubernetes_pod_annotation_promtail_path]
                    target_label: __path__
              - job_name: flow-nextjs-dev
                kubernetes_sd_configs:
                  - role: pod
                relabel_configs:
                  - source_labels: [__meta_kubernetes_pod_name]
                    regex: (flow-nextjs-dev-.*)
                    action: keep
                    target_label: pod_name
                  - source_labels: [__meta_kubernetes_namespace]
                    target_label: namespace
                  - source_labels: [__meta_kubernetes_pod_name]
                    target_label: pod_name
                  - source_labels: [__meta_kubernetes_pod_container_name]
                    target_label: container_name
                  - action: replace
                    source_labels: [__meta_kubernetes_pod_annotation_promtail_path]
                    target_label: __path__
                static_configs:
                  - targets: ['localhost']
                    labels:
                      job: flow-nextjs-dev
                      __path__: /var/log/flow-nextjs/*.log
          resources:
            requests:
              memory: "64Mi"
              cpu: "25m"
            limits:
              memory: "128Mi"
              cpu: "50m"
          tolerations:
            - key: "instance_type"
              operator: "Equal"
              value: "spot"
              effect: "NoSchedule"

        grafana:
          enabled: true
          image:
            tag: "latest"
          service:
            type: LoadBalancer
          adminPassword: "flow@grafana"
          resources:
            requests:
              memory: "64Mi"
              cpu: "25m"
            limits:
              memory: "128Mi"
              cpu: "50m"
          tolerations:
            - key: "instance_type"
              operator: "Equal"
              value: "spot"
              effect: "NoSchedule"
          persistence:
            enabled: true
            size: 5Gi
            storageClassName: standard

        prometheus:
          enabled: true
          alertmanager:
            persistentVolume:
              enabled: false
          server:
            persistentVolume:
              enabled: false
          pushgateway:
            enabled: true
            resources:
              requests:
                memory: "64Mi"
                cpu: "50m"
              limits:
                memory: "128Mi"
                cpu: "100m"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          tolerations:
            - key: "instance_type"
              operator: "Equal"
              value: "spot"
              effect: "NoSchedule"
