loki:
  enabled: true
  image:
    tag: "latest"
  persistence:
    enabled: true
    storageClassName: standard
    size: 5Gi
  readinessProbe:
    httpGet:
      path: /ready
      port: http-metrics
    initialDelaySeconds: 45
  livenessProbe:
    httpGet:
      path: /ready
      port: http-metrics
    initialDelaySeconds: 45
  storage:
    bucketNames:
      chunks: "loki-chunks" # 필요에 따라 버킷 이름을 지정
  config:
    auth_enabled: false
    server:
      http_listen_port: 3100
    ingester:
      lifecycler:
        address: 127.0.0.1
        ring:
          kvstore:
            store: inmemory
    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 168h
    storage_config:
      boltdb_shipper:
        active_index_directory: /var/loki/index
        cache_location: /var/loki/cache
        cache_ttl: 24h
        shared_store: filesystem
      filesystem:
        directory: /var/loki/chunks
    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
    chunk_store_config:
      max_look_back_period: 0s
    table_manager:
      retention_deletes_enabled: true
      retention_period: 168h

promtail:
  enabled: true
  image:
    tag: "latest"
  config:
    clients:
      - url: http://loki.monitoring:3100/loki/api/v1/push
    positions:
      filename: /run/promtail/positions.yaml
    scrape_configs:
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_name]
            target_label: __service__
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod_name
          - source_labels: [__meta_kubernetes_pod_container_name]
            target_label: container_name
          - action: replace
            source_labels: [__meta_kubernetes_pod_annotation_promtail_path]
            target_label: __path__
      - job_name: flow-nextjs-dev
        static_configs:
          - targets: ["localhost"]
            labels:
              job: flow-nextjs-dev
              __path__: /var/log/flow-nextjs/*.log

grafana:
  enabled: true
  image:
    tag: "latest"
  service:
    type: LoadBalancer
  adminPassword: "flow@grafana"
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Loki
          type: loki
          url: http://loki.monitoring:3100
          access: proxy
          isDefault: true

prometheus:
  enabled: true
  alertmanager:
    persistentVolume:
      enabled: false
  server:
    persistentVolume:
      enabled: false
