apiVersion: apps/v1
kind: Deployment
metadata:
  name: flow-api-gateway-prd
  namespace: flow
  labels:
    app: flow-api-gateway-prd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flow-api-gateway-prd
  template:
    metadata:
      labels:
        app: flow-api-gateway-prd
    spec:
      containers:
        - name: flow-api-gateway-prd
          image: asia-northeast3-docker.pkg.dev/code-review-platform-flow/flow-prd/flow-api-gateway-prd:7f02037b8133ea53ee479756a950228b5b8e6c3f
          ports:
            - containerPort: 8080
          env:
            - name: PROFILE
              value: "prd"
          volumeMounts:
            - name: log-volume
              mountPath: /var/log/flow
      tolerations:
        - key: "instance_type"
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: team
                    operator: In
                    values:
                      - devops
      volumes:
        - name: log-volume
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: flow-api-gateway-prd-service
  namespace: flow
spec:
  selector:
    app: flow-api-gateway-prd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
