apiVersion: apps/v1
kind: Deployment
metadata:
  name: flow-nextjs-prd
  namespace: flow
  labels:
    app: flow-nextjs-prd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flow-nextjs-prd
  template:
    metadata:
      labels:
        app: flow-nextjs-prd
    spec:
      containers:
        - name: flow-nextjs-prd
          image: asia-northeast3-docker.pkg.dev/code-review-platform-flow/flow-prd/flow-nextjs-prd:acaac5f1c8f59584646f09fb2aeba2f580ae5703
          ports:
            - containerPort: 3000
          env:
            - name: APP_ENV
              value: "production"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: flow-nextjs-prd-service
  namespace: flow
spec:
  selector:
    app: flow-nextjs-prd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
