apiVersion: v1
kind: Secret
metadata:
  name: flow-auth-prd-secret
  namespace: flow
type: Opaque
data:
  DB_URL: amRiYzpwb3N0Z3Jlc3FsOi8vMzQuMjIuMTA5LjExNjo1NDMyL2Zsb3ctcG9zdGdyZXNxbC1wcmQ=
  DB_USERNAME: Zmxvdy1hZG1pbi1wcmQ=
  DB_PASSWORD: Zmxvdy1wcmQ=
