apiVersion: apps/v1
kind: Deployment
metadata:
  name: flow-main-prd
  namespace: flow
  labels:
    app: flow-main-prd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flow-main-prd
  template:
    metadata:
      labels:
        app: flow-main-prd
    spec:
      containers:
        - name: flow-main-prd
          image: asia-northeast3-docker.pkg.dev/code-review-platform-flow/flow-prd/flow-main-prd:a0f7594f85e25bb594030fee316619e4adf5ba5a
          ports:
            - containerPort: 8080
          env:
            - name: PROFILE
              value: "prd"
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: flow-main-prd-secret
                  key: DB_URL
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: flow-main-prd-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: flow-main-prd-secret
                  key: DB_PASSWORD
          volumeMounts:
            - name: log-volume
              mountPath: /var/log/flow
      tolerations:
        - key: "instance_type"
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: team
                    operator: In
                    values:
                      - devops
      volumes:
        - name: log-volume
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: flow-main-prd-service
  namespace: flow
spec:
  selector:
    app: flow-main-prd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
