apiVersion: apps/v1
kind: Deployment
metadata:
  name: flow-nextjs-dev
  namespace: flow
  labels:
    app: flow-nextjs-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flow-nextjs-dev
  template:
    metadata:
      labels:
        app: flow-nextjs-dev
    spec:
      containers:
        - name: flow-nextjs-dev
          image: asia-northeast3-docker.pkg.dev/code-review-platform-flow/flow-dev/flow-nextjs-dev:c26ee68db5654a519dc283ef341d45d8180f0ad7
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "dev"
          volumeMounts:
            - name: log-volume
              mountPath: /var/log/flow-nextjs
      volumes:
        - name: log-volume
          emptyDir: {}
      imagePullSecrets:
        - name: artifact-registry-secret

---
apiVersion: v1
kind: Service
metadata:
  name: flow-nextjs-dev-service
  namespace: flow
spec:
  selector:
    app: flow-nextjs-dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
    - protocol: TCP
      port: 6006
      targetPort: 6006
  type: LoadBalancer
