apiVersion: apps/v1
kind: Deployment
metadata:
  name: flow-nextjs-dev
  namespace: flow
  labels:
    app: flow-nextjs-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flow-nextjs-dev
  template:
    metadata:
      labels:
        app: flow-nextjs-dev
    spec:
      containers:
        - name: flow-nextjs-dev
          image: asia-northeast3-docker.pkg.dev/code-review-platform-flow/flow-dev/flow-nextjs-dev:02771f90ecf619b457b5d06a9315a849246fbc24
          ports:
            - containerPort: 3000
          env:
            - name: APP_ENV
              value: "development"
          volumeMounts:
            - name: log-volume
              mountPath: /var/log/flow-nextjs
      volumes:
        - name: log-volume
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: flow-nextjs-dev-service
  namespace: flow
spec:
  selector:
    app: flow-nextjs-dev
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
