apiVersion: apps/v1
kind: Deployment
metadata:
  name: flow-nextjs-dev
  namespace: flow
  labels:
    app: flow
    service: flow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flow-nextjs-dev
      service: flow
  template:
    metadata:
      labels:
        app: flow-nextjs-dev
        service: flow
    spec:
      containers:
        - name: flow-nextjs-dev
          image: asia-northeast3-docker.pkg.dev/gcuflow/flow-dev/flow-nextjs-dev:b70b69d96b3a917b33283572b56798bf63e0b0aa
          ports:
            - containerPort: 3000
          env:
            - name: APP_ENV
              value: "development"
      tolerations:
        - key: "instance_type"
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: team
                    operator: In
                    values:
                      - devops
      volumes:
        - name: log-volume
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: flow-nextjs-dev-service
  namespace: flow
spec:
  selector:
    app: flow-nextjs-dev
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
