apiVersion: apps/v1
kind: Deployment
metadata:
  name: flow-nextjs-dev
  namespace: flow
  labels:
    app: flow-nextjs-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flow-nextjs-dev
  template:
    metadata:
      labels:
        app: flow-nextjs-dev
    spec:
      containers:
        - name: flow-nextjs-dev
          image: asia-northeast3-docker.pkg.dev/code-review-platform-flow/flow-dev/flow-nextjs-dev:61a239e9010bcc4a6a585d48a9d0d42bb14629fc
          ports:
            - containerPort: 3000
          env:
            - name: APP_ENV
              value: "development"
      tolerations:
        - key: "instance_type"
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: team
                    operator: In
                    values:
                      - devops
      volumes:
        - name: log-volume
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: flow-nextjs-dev-service
  namespace: flow
spec:
  selector:
    app: flow-nextjs-dev
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
