apiVersion: apps/v1
kind: Deployment
metadata:
  name: flow-nextjs-dev
  namespace: flow
  labels:
    app: flow-nextjs-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flow-nextjs-dev
  template:
    metadata:
      labels:
        app: flow-nextjs-dev
    spec:
      containers:
        - name: flow-nextjs-dev
          image: asia-northeast3-docker.pkg.dev/code-review-platform-flow/flow-dev/flow-nextjs-dev:2007d48e1a20c690943475b891e170c5315ce181
          ports:
            - containerPort: 3000
          env:
            - name: APP_ENV
              value: "development"
            - name : VITE_TOSS_CLIENT_KEY
              value : "test_ck_0RnYX2w5327goRzl1J1RVNeyqApQ"
            - name : VITE_TOSS_SECERET_KEY
              value : "test_sk_yL0qZ4G1VOdD0aBmoE0kroWb2MQY"
          volumeMounts:
            - name: log-volume
              mountPath: /var/log/flow-nextjs
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
      tolerations:
        - key: "instance_type"
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: team
                    operator: In
                    values:
                      - devops
      volumes:
        - name: log-volume
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: flow-nextjs-dev-service
  namespace: flow
spec:
  selector:
    app: flow-nextjs-dev
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
