apiVersion: apps/v1
kind: Deployment
metadata:
  name: flow-nextjs-dev
  labels:
    app: flow-nextjs-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flow-nextjs-dev
  template:
    metadata:
      labels:
        app: flow-nextjs-dev
    spec:
      containers:
        - name: flow-nextjs-dev
          image: asia-northeast3-docker.pkg.dev/code-review-platform-flow/flow-dev:d980d922875bd8c3636bdbf638f1c58dd1dd790b
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "dev"
      imagePullSecrets:
        - name: artifact-registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: flow-nextjs-dev-service
spec:
  selector:
    app: flow-nextjs-dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
