apiVersion: apps/v1
kind: Deployment
metadata:
  name: flow-file-dev
  namespace: flow
  labels:
    app: flow
    service: flow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flow-file-dev
      service: flow
  template:
    metadata:
      labels:
        app: flow-file-dev
        service: flow
    spec:
      containers:
        - name: flow-file-dev
          image: asia-northeast3-docker.pkg.dev/code-review-platform-flow/flow-dev/flow-file-dev:cd49b64edb3f6260745df44146ba0693562c07c2
          ports:
            - containerPort: 8080
          env:
            - name: PROFILE
              value: "dev"
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: flow-file-dev-secret
                  key: DB_URL
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: flow-file-dev-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: flow-file-dev-secret
                  key: DB_PASSWORD
            - name: GCP_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: flow-file-dev-secret
                  key: GCP_PROJECT_ID
            - name: GCP_STORAGE_BUCKET
              valueFrom:
                secretKeyRef:
                  name: flow-file-dev-secret
                  key: GCP_STORAGE_BUCKET
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/gcp-key.json
          volumeMounts:
            - name: log-volume
              mountPath: /var/log/flow
            - name: gcp-key-volume
              mountPath: /var/secrets
              readOnly: true
      tolerations:
        - key: "instance_type"
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: team
                    operator: In
                    values:
                      - devops
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              service: flow
      volumes:
        - name: log-volume
          emptyDir: {}
        - name: gcp-key-volume
          secret:
            secretName: flow-file-dev-secret

---
apiVersion: v1
kind: Service
metadata:
  name: flow-file-dev-service
  namespace: flow
spec:
  selector:
    app: flow-file-dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
