apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-application
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus
    targetRevision: 15.7.1
    helm:
      values: |
        alertmanager:
          enabled: true
          persistentVolume:
            enabled: false
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
        server:
          persistentVolume:
            enabled: false
          server:
            resources:
              limits:
                cpu: 200m
                memory: 256Mi
              requests:
                cpu: 100m
                memory: 128Mi
        pushgateway:
          enabled: true
          persistentVolume:
            enabled: false
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
        nodeExporter:
          enabled: true
          resources:
            limits:
              cpu: 50m
              memory: 64Mi
            requests:
              cpu: 25m
              memory: 32Mi
