apiVersion: apps/v1
kind: Deployment
metadata:
  name: flow-payment-dev
  namespace: flow
  labels:
    app: flow-payment-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flow-payment-dev
  template:
    metadata:
      labels:
        app: flow-payment-dev
    spec:
      containers:
        - name: flow-payment-dev
          image: asia-northeast3-docker.pkg.dev/code-review-platform-flow/flow-dev/flow-payment-dev:56aaca62f30b4dfa0d065b79d72b2f64cf701410
          ports:
            - containerPort: 8080
          env:
            - name: PROFILE
              value: "dev"
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: flow-payment-dev-secret
                  key: DB_URL
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: flow-payment-dev-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: flow-payment-dev-secret
                  key: DB_PASSWORD
            - name: WIDGET_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: flow-payment-dev-secret
                  key: WIDGET_SECRET_KEY
          volumeMounts:
            - name: log-volume
              mountPath: /var/log/flow
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
      volumes:
        - name: log-volume
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: flow-payment-dev-service
  namespace: flow
spec:
  selector:
    app: flow-payment-dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
