apiVersion: apps/v1
kind: Deployment
metadata:
  name: flow-payment-dev
  namespace: flow
  labels:
    app: flow
    service: flow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flow-payment-dev
      service: flow
  template:
    metadata:
      labels:
        app: flow-payment-dev
        service: flow
    spec:
      containers:
        - name: flow-payment-dev
          image: asia-northeast3-docker.pkg.dev/gcuflow/flow-dev/flow-payment-dev:27fa347c9ecbe5807bbd55ecd00efaf634077a7f
          ports:
            - containerPort: 8080
          env:
            - name: PROFILE
              value: "dev"
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: flow-payment-dev-secret
                  key: DB_URL
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: flow-payment-dev-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: flow-payment-dev-secret
                  key: DB_PASSWORD
            - name: WIDGET_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: flow-payment-dev-secret
                  key: WIDGET_SECRET_KEY
          volumeMounts:
            - name: log-volume
              mountPath: /var/log/flow
      tolerations:
        - key: "instance_type"
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: team
                    operator: In
                    values:
                      - devops
      volumes:
        - name: log-volume
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: flow-payment-dev-service
  namespace: flow
spec:
  selector:
    app: flow-payment-dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
