apiVersion: apps/v1
kind: Deployment
metadata:
  name: flow-main-dev
  namespace: flow
  labels:
    app: flow
    service: flow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flow-main-dev
      service: flow
  template:
    metadata:
      labels:
        app: flow-main-dev
        service: flow
    spec:
      containers:
        - name: flow-main-dev
          image: asia-northeast3-docker.pkg.dev/code-review-platform-flow/flow-dev/flow-main-dev:c689a94dc121d8afa9e16ed4eda4147d8127c704
          ports:
            - containerPort: 8080
          env:
            - name: PROFILE
              value: "dev"
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: flow-main-dev-secret
                  key: DB_URL
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: flow-main-dev-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: flow-main-dev-secret
                  key: DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: flow-main-dev-secret
                  key: JWT_SECRET
            - name: ACCESS_EXPIRATION
              valueFrom:
                secretKeyRef:
                  name: flow-main-dev-secret
                  key: ACCESS_EXPIRATION
            - name: REFRESH_EXPIRATION
              valueFrom:
                secretKeyRef:
                  name: flow-main-dev-secret
                  key: REFRESH_EXPIRATION
            - name: PROFILE_URL
              valueFrom:
                secretKeyRef:
                  name: flow-main-dev-secret
                  key: PROFILE_URL
            - name: UNIV_API_KEY
              valueFrom:
                secretKeyRef:
                  name: flow-main-dev-secret
                  key: UNIV_API_KEY
            - name: UPLOAD_URL
              valueFrom:
                secretKeyRef:
                  name: flow-main-dev-secret
                  key: UPLOAD_URL
            - name: UPLOAD_PATH
              valueFrom:
                secretKeyRef:
                  name: flow-main-dev-secret
                  key: UPLOAD_PATH
          volumeMounts:
            - name: log-volume
              mountPath: /var/log/flow
      tolerations:
        - key: "instance_type"
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: team
                    operator: In
                    values:
                      - devops
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - flow-main-dev
            topologyKey: "kubernetes.io/hostname"
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: flow-main-dev
              service: flow
      volumes:
        - name: log-volume
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: flow-main-dev-service
  namespace: flow
spec:
  selector:
    app: flow-main-dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
