apiVersion: apps/v1
kind: Deployment
metadata:
  name: flow-admin-main-dev
  namespace: flow
  labels:
    app: flow-admin-main-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flow-admin-main-dev
  template:
    metadata:
      labels:
        app: flow-admin-main-dev
    spec:
      containers:
        - name: flow-admin-main-dev
          image: asia-northeast3-docker.pkg.dev/code-review-platform-flow/flow-dev/flow-admin-main-dev:b7f400a4021e7c6dca84a66350bbbb9e53e5947f
          ports:
            - containerPort: 8080
          env:
            - name: PROFILE
              value: "dev"
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: flow-admin-main-dev-secret
                  key: DB_URL
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: flow-admin-main-dev-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: flow-admin-main-dev-secret
                  key: DB_PASSWORD
          volumeMounts:
            - name: log-volume
              mountPath: /var/log/flow
      tolerations:
        - key: "instance_type"
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: team
                    operator: In
                    values:
                      - devops
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: flow-admin-main-dev
      volumes:
        - name: log-volume
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: flow-admin-main-dev-service
  namespace: flow
spec:
  selector:
    app: flow-admin-main-dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
