apiVersion: v1
kind: Secret
metadata:
  name: flow-admin-main-dev-secret
  namespace: flow
type: Opaque
data:
  DB_URL: amRiYzpwb3N0Z3Jlc3FsOi8vMzQuNjQuMTAyLjEyMjo1NDMyL2Zsb3ctcG9zdGdyZXNxbC1kZXYK
  DB_USERNAME: Zmxvdy1hZG1pbi1kZXY=
  DB_PASSWORD: Zmxvdy1kZXY=
